# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYuTV' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYuTV
pod 'Alamofire', '~> 4.1.0'

end
